### ISSUE TITLE
sql files in wrong directory to initialize the DB.

### ISSUE THREAD

**Issue by sredbull** [Yapeal/yapeal-ng#2]
I had to manually move the sql files in /lib/Sql (and the updates folder) to /lib/Sql/Database/ for the php bin/yc D:I to work.

**Comment by Dragonrun1** [comment]
Actual Database stuff is going away / moving to Sql instead. BTW at this time Yapeal-ng only creates the DB but does NOT create any of the tables because the new code has not been completed yet. To make it easier for new API create code to work each API or possible every table will end up in their own files. For example where there were lib/Sql/Create*Tables.sql before there will be now be lib/Sql/{section}/{api}.sql or lib/Sql/{section}/{table}.sql. My current thinking is per API but if per table is easier I'll switch. Updates should be mostly unchanged and still use a date-time based name.

Also make sure you check out the latest push as there are several things in it the have to do with config changes for the directories etc.

**Comment by Dragonrun1** [comment]
'bin/yc D:I' now expect to find Create*.sql files in correct directory.
